export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOADING_USER_PROFILE = 'LOADING_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';

export const LOAD_USER_DEVICES_SUCCESS = 'LOAD_USER_DEVICES_SUCCESS';
export const LOADING_USER_DEVICES = 'LOADING_USER_DEVICES';
export const CREATE_USER_DEVICE_SUCCESS = 'CREATE_USER_DEVICE_SUCCESS';
export const CREATING_USER_DEVICE = 'CREATING_USER_DEVICE';

export const LOAD_DEVICE_TYPES_SUCCESS = 'LOAD_DEVICE_TYPES_SUCCESS';
export const LOADING_DEVICE_TYPES = 'LOADING_DEVICE_TYPES';

export const LOAD_DEVICE_BRANDS_SUCCESS = 'LOAD_DEVICE_BRANDS_SUCCESS';
export const LOADING_DEVICE_BRANDS = 'LOADING_DEVICE_BRANDS';